ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: check-yaml

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black-jupyter

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.14.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.3.0]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.275
  hooks:
  - id: ruff
    args:
      - --quiet
      - --fix

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
  - id: nbqa-ruff
    args:
      - --quiet
      - --fix
      - --extend-ignore=B018,E402

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
  - id: nbstripout

- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.2
  hooks:
  - id: markdown-toc
    files: README.md
