target-version = "py38"

# Enable flake8-bugbear (`B`) rules.
select = ["E", "W", "F", "B", "I", "UP"]

ignore = [
	"E501",  # Never enforce `E501` (line length violations)
	"E402",  # Never enforce `E402` (import not at top of file)
]
